version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: chess-redis-cache
    command: >
      redis-server
      --maxmemory 8gb
      --maxmemory-policy noeviction
      --save 60 1000
      --appendonly yes
      --appendfsync everysec
    ports:
      - "6381:6379"
    volumes:
      - ./storage/redis-data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s
    networks:
      - chess-network

networks:
  chess-network:
    driver: bridge

volumes:
  redis-data:
    driver: local
