# Node configuration
node_id: "agg_004"
cluster_id: "cluster_aggressive"

# Server connection
server_host: "localhost"
server_port: 8765

# Trainer configuration
trainer_type: "dummy"  # Options: dummy, supervised, alphazero
auto_reconnect: true

# Training parameters
training:
  games_per_round: 100
  batch_size: 32
  learning_rate: 0.001
  exploration_factor: 1.0
  max_game_length: 200
  save_games: true
  playstyle: "aggressive"  # Or "positional"

# Storage configuration
storage:
  enabled: false
  base_path: "./storage"
  save_models: true
  save_metrics: true
  save_games: true

# Logging configuration
logging:
  level: "DEBUG"  # DEBUG, INFO, WARNING, ERROR
  file: null  # Set to path for file logging
  format: "text"  # text or json
